server {
    listen 80;

    location /api/ {
        proxy_set_header Host $http_host;
        proxy_pass http://backend:8000/api/;
    }

    location /admin/ {
        proxy_set_header Host $http_host;
        proxy_pass http://backend:8000/admin/;
    }

    # Статика админки и rest_framework (лежат в корне /staticfiles/)
    location /static/admin/ {
        alias /staticfiles/static/admin/;
    }

    location /static/rest_framework/ {
        alias /staticfiles/static/rest_framework/;
    }

    # Статика фронтенда (лежит в /staticfiles/static/)
    location /static/ {
        alias /staticfiles/static/;
    }

    # Всё остальное — фронтенд
    location / {
        alias /staticfiles/;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}